services:
  postgres:
    profiles: [ "dev", "prod" ]
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-vol:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rbac-net

  keydb:
    profiles: [ "dev", "prod" ]
    image: eqalpha/keydb:latest
    command: keydb-server --requirepass ${KDB_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
    volumes:
      - keydb-vol:/data
    healthcheck:
      test: [ "CMD", "keydb-cli", "-a", "${KDB_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rbac-net

  rbac-migration-dev:
    profiles: [ "dev" ]
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src/rbac:/app/src/rbac
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rbac-net

  rbac-dev:
    profiles: [ "dev" ]
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3100:80"
    restart: unless-stopped
    command: uvicorn rbac.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./src/rbac:/app/src/rbac
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/ping || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy
      rbac-migration-dev:
        condition: service_completed_successfully
    networks:
      - rbac-net

  rbac-migration-prod:
    profiles: [ "prod" ]
    image: ghcr.io/desspperate/rbac:latest
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rbac-net

  rbac-prod:
    profiles: [ "prod" ]
    image: ghcr.io/desspperate/rbac:latest
    env_file:
      - .env
    ports:
      - "127.0.0.1:3100:80"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/ping || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy
      rbac-migration-prod:
        condition: service_completed_successfully
    networks:
      - rbac-net

volumes:
  postgres-vol:
    driver: local
  keydb-vol:
    driver: local

networks:
  rbac-net:
    driver: bridge
