from enum import Enum


class ForcedSessionStatusEnum(Enum):
    LOGGED_OUT = "LOGGED_OUT"
    TERMINATED_BY_ADMIN = "TERMINATED_BY_ADMIN"
    TERMINATED_DUE_TO_SUSPICIOUS_ACTIVITY = "TERMINATED_DUE_TO_SUSPICIOUS_ACTIVITY"
