from enum import StrEnum


class AccessTokenStatusEnum(StrEnum):
    WRONG_TYPE = "WRONG_TYPE"
    EXPIRED = "EXPIRED"
    TOKEN_REVOKED = "TOKEN_REVOKED"  #  noqa: S105
    SESSION_REVOKED = "SESSION_REVOKED"
    VALID = "VALID"


class TokenPairStatusEnum(StrEnum):
    ACCESS_NOT_FOUND = "ACCESS_NOT_FOUND"
    REFRESH_NOT_FOUND = "REFRESH_NOT_FOUND"
    ACCESS_WRONG_TYPE = "ACCESS_WRONG_TYPE"
    REFRESH_WRONG_TYPE = "REFRESH_WRONG_TYPE"
    SESSION_MISMATCH = "SESSION_MISMATCH"
    SESSION_REVOKED = "SESSION_REVOKED"
    ACCESS_REVOKED = "ACCESS_REVOKED"
    REFRESH_REVOKED = "REFRESH_REVOKED"
    ACCESS_EXPIRED = "ACCESS_EXPIRED"
    REFRESH_EXPIRED = "REFRESH_EXPIRED"
    VALID = "VALID"
