"""Initial migration

Revision ID: 96852f4cc5fe
Revises:
Create Date: 2026-04-27 13:10:25.900159

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96852f4cc5fe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("permissions",
    sa.Column("codename", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=1000), nullable=True),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("codename ~ '^[a-z]+(\\.[a-z]+)*$'", name="ck_permission_codename_pattern"),
    sa.CheckConstraint('description ~ \'^[a-zA-Zа-яА-ЯёЁ0-9\\s.,!?:;()\\"\\\'\'\\-_]+$\'',
                       name="ck_permission_description_pattern"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("codename", name="uq_permission_codename"),
    )
    op.create_table("roles",
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=1000), nullable=True),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("name ~ '^[a-z]+(_[a-z]+)*$'", name="ck_role_name_pattern"),
    sa.CheckConstraint('description ~ \'^[a-zA-Zа-яА-ЯёЁ0-9\\s.,!?:;()\\"\\\'\'\\-_]+$\'',
                       name="ck_role_description_pattern"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name", name="uq_role_name"),
    )
    op.create_table("users",
    sa.Column("username", sa.String(length=32), nullable=False),
    sa.Column("password_hash", sa.String(length=128), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("username ~ '^[a-z0-9]([a-z0-9._-]*[a-z0-9])?$'", name="ck_user_username_pattern"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("username", name="uq_user_username"),
    )
    op.create_table("role_permissions",
    sa.Column("role_id", sa.Integer(), nullable=False),
    sa.Column("permission_id", sa.Integer(), nullable=False),
    sa.Column("effect", sa.Enum("ALLOW", "DENY", name="policyeffectenum", native_enum=False), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], name="fk_role_permission_permission_id"),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name="fk_role_permission_role_id"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permission_role_permission"),
    )
    op.create_table("tokens",
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("token_hash", sa.String(length=128), nullable=False),
    sa.Column("token_type", sa.Enum("REFRESH", "ACCESS", name="tokentypeenum", native_enum=False), nullable=False),
    sa.Column("forced_status", sa.Enum("REVOKED_BY_OWNER", "REVOKED_BY_ADMIN", name="forcedtokenstatusenum",
                                       native_enum=False), nullable=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_token_user_id"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("token_hash", name="uq_token_token_hash"),
    )
    op.create_table("user_permissions",
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("permission_id", sa.Integer(), nullable=False),
    sa.Column("effect", sa.Enum("ALLOW", "DENY", name="policyeffectenum", native_enum=False), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], name="fk_user_permission_permission_id"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_permission_user_id"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "permission_id", name="uq_user_permission_user_permission"),
    )
    op.create_table("user_roles",
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("role_id", sa.Integer(), nullable=False),
    sa.Column("effect", sa.Enum("ALLOW", "DENY", name="policyeffectenum", native_enum=False), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name="fk_user_role_role_id"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_role_user_id"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("role_id", "user_id", name="uq_user_role_user_role"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("user_permissions")
    op.drop_table("tokens")
    op.drop_table("role_permissions")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
